name: Build, Test, & Deploy to EC2

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-migrations:
    name: Run DB Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.3/migrate.linux-amd64.tar.gz | tar xz
          sudo mv migrate /usr/local/bin/

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          migrate -verbose -database "$DATABASE_URL" -path ./migrations up

  build-test-deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: run-migrations

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Run tests
        run: go test -v ./...

      - name: Build Docker image
        run: docker build -t habit-tracker-go .

      - name: Save Docker image to tar
        run: docker save habit-tracker-go > habit-tracker-go.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "habit-tracker-go.tar"
          target: "~/"

      - name: SSH into EC2 to load/run container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # load image
            docker load < ~/habit-tracker-go.tar

            # stop and remove old container
            docker stop habit-tracker-go || true
            docker rm habit-tracker-go || true

            # run new container
            docker run -d --name habit-tracker-go \
              --env-file .env \
              -p ${{ secrets.PORT }}:8080 habit-tracker-go
